name: east_asian_width
description: A lightweight library for detecting East Asian Width of Unicode characters. Useful for text layout and alignment.
homepage: https://www.marinvitlov.com

version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
